### ISSUE TITLE
default password

### ISSUE THREAD

**Issue by rangez** [Ostaer/FlexGW#1]
我在我自己的服务器上搭建了一整套环境，并且它可以正常启动，我已经到了浏览器登录页面，但是初始的账户和密码是什么呢？我没有在readme文件或者部署文档中找到，希望得到帮助，谢谢！

**Comment by carbule** [comment]
系统用户名和密码

**Comment by rangez** [comment]
> 系统用户名和密码

感谢，我已经找到了
